# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
             login_path: less_mpcu_index
             check_path: less_mpcu_login

    access_control:
        - { path: ^/home, roles: ROLE_USER }

    providers:
        main:
          entity:
            class: Less\MpcuBundle\Entity\UserSession
            property: username

    encoders:
        Less\MpcuBundle\Entity\UserSession: sha512