<?php

namespace Less\MpcuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Less\MpcuBundle\LessMpcuBundle;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
	public function addAction($session_id,$type, $handling ){
		$em = $this->getEntityManager();
		$action = new Action();
		$action->setHandling($handling);
		$action->setType($type);
		$action->setSessionId($session_id);
		$now = new \DateTime('now');
		$action->setTime($now->getTimestamp());
		$em->persist($action);
		$em->flush();
	}
	public function getNextActions($session_id, $last_action_time){
		$em = $this->getEntityManager();
		$query = $em->createQuery('
				SELECT action
				FROM LessMpcuBundle:Action action
				WHERE action.time > :last_action_time AND action.session_id = :session_id
				ORDER BY action.time ASC')
				->setParameter('last_action_time', $last_action_time)
				->setParameter('session_id', $session_id);
		return $query->getResult();
	}
}
