<?php

namespace Less\MpcuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Less\MpcuBundle\LessMpcuBundle;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
	public function saveAction($action){
		$em = $this->getEntityManager();
		$now = new \DateTime('now');
		$action->setTime($now->getTimestamp());
		$em->persist($action);
		$em->flush();
	}
	public function getNextActions($session, $last_action_time){
		$qb = $this->createQueryBuilder('a');
		$query = $qb
			->where('a.session = :session AND a.time > :last_action_time')
			->setParameter('session', $session->getId())
			->setParameter('last_action_time', $last_action_time)
			->orderBy('a.time', 'ASC')
			->getQuery();
		
		return $query->getResult();
	}
	
	
}
