<?php

namespace Less\MpcuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManager;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{	
	public function saveSession($session){
		$now = new \DateTime('now');
		$session->setTime($now->getTimestamp());
		$em = $this->getEntityManager();
		$em->persist($session);
		$em->flush();
		//TODO: replace call on saveSession with automatic execution once a day like cron job
		$this->cleanUp();
	}
	/** 
	 * 	 to remove old user sessions which were older than 2 days
	 */
	public function cleanUp(){
		$past = new \DateTime('now');
		$past->sub((new \DateInterval('P2D')));
		
		$qb = $this->createQueryBuilder('s');
		$qb->delete('Session')
			->where('s.createTime < :past')
			->setParamter('past', $past->getTimestamp())
			->getQuery()->getResult();
	}
	
	public function exists($name){
		$qb = $this->createQueryBuilder('s');
		$query = $qb->where('s.name = :name')
		->setParameter('name', $name)
		->getQuery();
		
		$res = $query->getResult();
		
		if(count($res) > 0){
			return true;
		}
		return false;
	}
}
