<?php

namespace Less\MpcuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManager;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
	
	
	public function createSession($name, $password){
		$em = $this->getEntityManager();
		$session = new Session();
		$session->setName($name);
		$session->setPassword($password);
		$em->persist($session);
	}
	public function exists($name){
		$qb = $this->createQueryBuilder('s');
		$query = $qb->where('s.name = :name')
		->setParameter('name', $name)
		->getQuery();
		
		$res = $query->getResult();
		
		if(count($res) > 0){
			return true;
		}
		return false;
	}
}
