<?php

namespace Less\MpcuBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManager;

/**
 * UserSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSessionRepository extends EntityRepository
{	
	public function saveSession($session){
		$now = new \DateTime('now');
		$session->setCreateTime($now->getTimestamp());
		$em = $this->getEntityManager();
		$em->persist($session);
		$em->flush();
		//TODO: replace call on saveSession with automatic execution once a day like cron job
		$this->cleanUp();
	}
	/** 
	 * 	 to remove old user sessions which were older than 2 days
	 */
	public function cleanUp(){
        //TODO: implement automatic cleanup of old usersession ..

	}
	
	public function exists($name){
		$qb = $this->createQueryBuilder('s');
		$query = $qb->where('s.username = :name')
		->setParameter('name', $name)
		->getQuery();
		
		$res = $query->getResult();
		
		if(count($res) > 0){
			return true;
		}
		return false;
	}
}
