less_mpcu_index:
  pattern: /
  defaults: { _controller: LessMpcuBundle:Default:index }
less_mpcu_login:
  pattern: /login
less_mpcu_register:
  pattern: /register
  defaults: { _controller: LessMpcuBundle:Default:register }
less_mpcu_register_create:
  pattern: /register/create
  defaults: { _controller: LessMpcuBundle:Default:create }
less_mpcu_home:
  pattern: /home
  defaults: { _controller: LessMpcuBundle:Home:index }
less_mpcu_home_sender:
  pattern: /home/sender
  defaults: { _controller: LessMpcuBundle:Home:sender }
less_mpcu_home_reciever:
  pattern: /home/reciever
  defaults: { _controller: LessMpcuBundle:Home:reciever }
less_mpcu_ajax_get_next:
  pattern: /ajax/get_next
  defaults: { _controller: LessMpcuBundle:Ajax:getNext }
less_mpcu_ajax_save:
  pattern: /ajax/save
  defaults: { _controller: LessMpcuBundle:Ajax:save }