parameters:
#    less_mpcu.example.class: Less\MpcuBundle\Example

services:
#    less_mpcu.example:
#        class: %less_mpcu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
